
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parse;

/** CUP generated interface containing symbol constants. */
public interface CUPToken {
  /* terminals */
  public static final int DIVIDE = 8;
  public static final int LBRACKET = 23;
  public static final int KW_PROCEDURE = 33;
  public static final int EQUALS = 9;
  public static final int PERIOD = 16;
  public static final int KW_DO = 28;
  public static final int LPAREN = 21;
  public static final int GREATER = 14;
  public static final int KW_CONST = 27;
  public static final int LESS = 13;
  public static final int MINUS = 6;
  public static final int RPAREN = 22;
  public static final int KW_RECORD = 35;
  public static final int SEMICOLON = 2;
  public static final int GEQUALS = 12;
  public static final int RANGE = 15;
  public static final int LEQUALS = 11;
  public static final int NEQUALS = 10;
  public static final int COMMA = 17;
  public static final int KW_WRITE = 40;
  public static final int PLUS = 5;
  public static final int KW_TYPE = 37;
  public static final int ASSIGN = 4;
  public static final int KW_NEW = 32;
  public static final int KW_CALL = 26;
  public static final int EOF = 0;
  public static final int RBRACKET = 24;
  public static final int KW_BEGIN = 25;
  public static final int error = 1;
  public static final int LCURLY = 19;
  public static final int NUMBER = 43;
  public static final int KW_IF = 31;
  public static final int RCURLY = 20;
  public static final int TIMES = 7;
  public static final int COLON = 3;
  public static final int ILLEGAL = 41;
  public static final int KW_END = 30;
  public static final int KW_ELSE = 29;
  public static final int KW_READ = 34;
  public static final int KW_VAR = 38;
  public static final int KW_WHILE = 39;
  public static final int KW_THEN = 36;
  public static final int POINTER = 18;
  public static final int IDENTIFIER = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "COLON",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "EQUALS",
  "NEQUALS",
  "LEQUALS",
  "GEQUALS",
  "LESS",
  "GREATER",
  "RANGE",
  "PERIOD",
  "COMMA",
  "POINTER",
  "LCURLY",
  "RCURLY",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "KW_BEGIN",
  "KW_CALL",
  "KW_CONST",
  "KW_DO",
  "KW_ELSE",
  "KW_END",
  "KW_IF",
  "KW_NEW",
  "KW_PROCEDURE",
  "KW_READ",
  "KW_RECORD",
  "KW_THEN",
  "KW_TYPE",
  "KW_VAR",
  "KW_WHILE",
  "KW_WRITE",
  "ILLEGAL",
  "IDENTIFIER",
  "NUMBER"
  };
}

